apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo
  labels:
    app: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/tomkukral/training-model.git
    targetRevision: HEAD
    path: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
